name: PSC Free Dumper

on:
  repository_dispatch:
    types: [PSCtrigger]

jobs:
  free-dumper-job:
    if: ${{ github.event.client_payload.tag == 'PSCtrigger-Free' }}
    runs-on: windows-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Clone Private Repository
        shell: pwsh
        run: |
          git clone --depth=1 https://x-access-token:${{ secrets.KTNTOKEN }}@github.com/PrimeStudentCouncil/BlueArchiveAutoDump.git source

      - name: Install dependencies from private repo
        shell: pwsh
        working-directory: source
        run: |
          if (Test-Path requirements.txt) {
            pip install -r requirements.txt
          }

      - name: Run main.py from private repo
        shell: pwsh
        working-directory: source
        run: python main.py

      - name: Push dump_extracted/Japan & Global with versioned commit message
        shell: pwsh
        run: |
          function Test-DumpFolderValid {
            param([string]$basePath)
            $requiredFolders = @("Excel", "ExcelDB", "HexaMap")
            foreach ($folder in $requiredFolders) {
              $fullPath = Join-Path $basePath $folder
              if (-not (Test-Path $fullPath)) {
                Write-Host "Missing folder: $fullPath"
                return $false
              }
              if (-not (Test-Path "$fullPath\*" -PathType Leaf)) {
                Write-Host "Folder empty: $fullPath"
                return $false
              }
            }
            return $true
          }

          # 这里的路径指向工作目录下的 dump_extracted
          $japanPath = ".\dump_extracted\Japan"
          $globalPath = ".\dump_extracted\Global"

          Write-Host "Checking Japan dump folders validity..."
          $validJapan = Test-DumpFolderValid -basePath $japanPath
          Write-Host "Japan valid: $validJapan"

          Write-Host "Checking Global dump folders validity..."
          $validGlobal = Test-DumpFolderValid -basePath $globalPath
          Write-Host "Global valid: $validGlobal"

          if (-not $validJapan -and -not $validGlobal) {
            Write-Host "Neither Japan nor Global dumps are valid. Exiting early."
            exit 0
          }

          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          Write-Host "Cloning repository..."
          git clone --depth=1 https://x-access-token:${{ secrets.KTNTOKEN }}@github.com/PrimeStudentCouncil/BlueArchiveExcel.git PSCRepo

          Set-Location PSCRepo

          Write-Host "Cleaning old folders..."
          if (Test-Path Japan) { Remove-Item Japan -Recurse -Force }
          if (Test-Path Global) { Remove-Item Global -Recurse -Force }

          New-Item -ItemType Directory -Force -Path Japan | Out-Null
          New-Item -ItemType Directory -Force -Path Global | Out-Null

          if ($validJapan) {
            Write-Host "Copying Japan dump data..."
            Copy-Item "$japanPath\*" -Destination Japan\ -Recurse -Force
          }

          if ($validGlobal) {
            Write-Host "Copying Global dump data..."
            Copy-Item "$globalPath\*" -Destination Global\ -Recurse -Force
          }

          Write-Host "Staging files for commit..."
          git add Japan Global

          Write-Host "Files staged for commit:"
          git diff --cached --name-only

          $hasJapanChange = (git diff --cached --name-only Japan) -ne ''
          $hasGlobalChange = (git diff --cached --name-only Global) -ne ''

          Write-Host "Japan changes staged: $hasJapanChange"
          Write-Host "Global changes staged: $hasGlobalChange"

          if (-not $hasJapanChange -and -not $hasGlobalChange) {
            Write-Host "No changes detected, skipping commit and push."
            exit 0
          }

          try {
            $globalJson = Get-Content ..\source\GlobalConfig.json -Raw | ConvertFrom-Json
            $globalVersion = ($globalJson.resource_path -split '/')[ -2 ]
          } catch {
            $globalVersion = "unknown"
          }

          try {
            $jpJson = Get-Content ..\source\JapanConfig.json -Raw | ConvertFrom-Json
            $jpVerRoot = $null
            if ($jpJson.ConnectionGroups -and $jpJson.ConnectionGroups[0].OverrideConnectionGroups) {
              $grp = $jpJson.ConnectionGroups[0].OverrideConnectionGroups
              $jpVerRoot = if ($grp.Count -gt 1) { $grp[1].AddressablesCatalogUrlRoot } else { $grp[0].AddressablesCatalogUrlRoot }
            }
            $jpVersion = if ($jpVerRoot) { ($jpVerRoot -split '/')[ -1 ] } else { "unknown" }
          } catch {
            $jpVersion = "unknown"
          }

          $commitMessage = ""
          if ($hasJapanChange) { $commitMessage += "JP $jpVersion " }
          if ($hasGlobalChange) { $commitMessage += "GL $globalVersion" }
          $commitMessage = $commitMessage.Trim()

          Write-Host "Commit message: $commitMessage"

          Write-Host "Committing..."
          git commit -m $commitMessage
          if ($LASTEXITCODE -ne 0) {
            Write-Host "git commit failed with exit code $LASTEXITCODE"
            exit 1
          }

          Write-Host "Pushing to origin master..."
          git push origin master
          if ($LASTEXITCODE -ne 0) {
            Write-Host "git push failed with exit code $LASTEXITCODE"
            exit 1
          }

          Write-Host "Push completed successfully."
